export const POINTS='POINTS';
export const RESET_POINTS='RESET_POINTS';
export const NUEVA_REGION='NUEVA_REGION';
export const RESET_REGION='RESET_REGION';
export const OBTENER_DEMANDADOS_TABLE='OBTENER_DEMANDADOS_TABLE'
export const OBTENER_DEMANDADOS_TABLE_SUCCESS='OBTENER_DEMANDADOS_TABLE_SUCCESS'