export const GET_EMBARGOS_ALL='GET_EMBARGOS_ALL'
export const GET_EMBARGOS_ALL_SUCCESS='GET_EMBARGOS_ALL_SUCCESS'
export const GET_EMBARGOS_CONFIRMADOS='GET_EMBARGOS_CONFIRMADOS'
export const GET_EMBARGOS_CONFIRMADOS_SUCCESS='GET_EMBARGOS_CONFIRMADOS_SUCCESS'
export const GET_EMBARGOS_POR_CONFIRMAR='GET_EMBARGOS_POR_CONFIRMAR'
export const GET_EMBARGOS_POR_CONFIRMAR_SUCCESS='GET_EMBARGOS_POR_CONFIRMAR_SUCCESS'
export const GET_EMBARGOS_ASIGNADOS='GET_EMBARGOS_ASIGNADOS'
export const GET_EMBARGOS_ASIGNADOS_SUCCESS='GET_EMBARGOS_ASIGNADOS_SUCCESS'
export const GET_EMBARGO='GET_EMBARGO'
export const GET_DEMANDADOS='GET_DEMANDADOS'
export const GET_EMBARGO_SUCCESS='GET_EMBARGO_SUCCESS'
export const GET_DEMANDADOS_SUCCESS='GET_DEMANDADOS_SUCCESS'

//DELETE
export const DELETE_EMBARGO='DELETE_EMBARGO'
export const DELETE_DEMANDADO='DELETE_DEMANDADO'
export const DELETE_DEMANDANTE='DELETE_DEMANDANTE';
//UPDATE
export const UPDATE_DEMANDADO='UPDATE_DEMANDADO'
export const UPDATE_DEMANDANTE='UPDATE_DEMANDANTE'
//CREATE
export const CREATE_DEMANDADO='CREATE_DEMANDADO'
export const CREATE_DEMANDANTE='CREATE_DEMANDANTE'