export const GET_EMBARGOS_ALL='GET_EMBARGOS_ALL'
export const GET_EMBARGOS_ALL_SUCCESS='GET_EMBARGOS_ALL_SUCCESS'
export const GET_EMBARGOS_CONFIRMADOS='GET_EMBARGOS_CONFIRMADOS'
export const GET_EMBARGOS_CONFIRMADOS_SUCCESS='GET_EMBARGOS_CONFIRMADOS_SUCCESS'
export const GET_EMBARGOS_POR_CONFIRMAR='GET_EMBARGOS_POR_CONFIRMAR'
export const GET_EMBARGOS_POR_CONFIRMAR_SUCCESS='GET_EMBARGOS_POR_CONFIRMAR_SUCCESS'
export const GET_EMBARGOS_ASIGNADOS='GET_EMBARGOS_ASIGNADOS'
export const GET_EMBARGOS_ASIGNADOS_SUCCESS='GET_EMBARGOS_ASIGNADOS_SUCCESS'
export const GET_EMBARGO='GET_EMBARGO'
export const GET_DEMANDADOS='GET_DEMANDADOS'
export const GET_DEMANDADOS_UPDATE_TABLE='GET_DEMANDADOS_UPDATE_TABLE'
export const GET_DEMANDADOS_UPDATE_TABLE_SUCCESS='GET_DEMANDADOS_UPDATE_TABLE_SUCCESS'
export const GET_DEMANDANTES_UPDATE_TABLE_SUCCESS='GET_DEMANDANTES_UPDATE_TABLE_SUCCESS'
export const GET_EMBARGO_SUCCESS='GET_EMBARGO_SUCCESS'
export const GET_DEMANDADOS_SUCCESS='GET_DEMANDADOS_SUCCESS'

//DELETE
export const DELETE_EMBARGO='DELETE_EMBARGO'
export const DELETE_DEMANDADO='DELETE_DEMANDADO'
export const DELETE_DEMANDANTE='DELETE_DEMANDANTE';
//UPDATE
export const UPDATE_DEMANDADO='UPDATE_DEMANDADO'
export const UPDATE_DEMANDANTE='UPDATE_DEMANDANTE'
export const UPDATE_EMBARGO='UPDATE_EMBARGO'
export const UPDATE_ALL_TIPO_DOCUMENTO='UPDATE_ALL_TIPO_DOCUMENTO'
//CREATE
export const CREATE_DEMANDADO='CREATE_DEMANDADO'
export const CREATE_DEMANDANTE='CREATE_DEMANDANTE'

//CONFIRM
export const CONFIRMAR_EMBARGO='CONFIRMAR_EMBARGO';

//MENSAJES
export const NUEVO_MESANJE='NUEVO_MESANJE';
export const RESET_MENSAJE='RESET_MENSAJE'
//ENVIAR DEMANDADOS
export const SAVE_DEMANDADOS='SAVE_DEMANDADOS';
export const GET_DEMANDADOS_SUCCESS_TABLE='GET_DEMANDADOS_SUCCESS_TABLE'
export const CHANGE_SIGUIENTE='CHANGE_SIGUIENTE'
export const CHANGE_ANTERIOR='CHANGE_ANTERIOR'
export const GET_DEMANDADOS_SIGUIENTE='GET_DEMANDADOS_SIGUIENTE'
export const GET_DEMANDADOS_ANTERIOR='GET_DEMANDADOS_ANTERIOR'