export const CONTEO_EMBARGOS='CONTEO_EMBARGOS';
export const CONTEO_EMBARGOS_SUCCESS='CONTEO_EMBARGOS_SUCCESS';
export const STATS_USER='STATS_USER';
export const STATS_USER_SUCCESS='STATS_USER_SUCCESS';
export const STATS_GENERAL='STATS_GENERAL';
export const STATS_GENERAL_SUCCESS='STATS_GENERAL_SUCCESS';
export const STATS_RANKING_USER='STATS_RANKING_USER';