export const UPLOAD_EXCEL='UPLOAD_EXCEL'
export const UPLOAD_EXCEL_SUCCESS='UPLOAD_EXCEL_SUCCESS'
export const MENSAJE_EXCEL='MENSAJE_EXCEL'
export const RESET_MENSAJE_EXCEL='RESET_MENSAJE_EXCEL'
export const GET_PREVIEW='GET_PREVIEW';
export const GET_PREVIEW_SUCCESS='GET_PREVIEW_SUCCESS'
export const LOAD_DEMANDADOS='LOAD_DEMANDADOS'