export const UPLOAD_REQUEST='UPLOAD_REQUEST';
export const ADD_FILE='ADD_FILE';
export const UPLOAD_REQUEST_SUCCESS='UPLOAD_REQUEST_SUCCESS'
export const UPLOAD_REQUEST_FAILED='UPLOAD_REQUEST_FAILED'
export const UPDATE_LOADER='UPDATE_LOADER';
export const UPLOAD_MENSAJE='UPLOAD_MENSAJE';
export const RESET_MENSAJE='RESET_MENSAJE';
export const SET_POSITION_PROCESS='SET_POSITION_PROCESS';