export const UPLOAD_REQUEST='UPLOAD_REQUEST';
export const ADD_FILE='ADD_FILE';
export const UPLOAD_REQUEST_SUCCESS='UPLOAD_REQUEST_SUCCESS'
export const UPLOAD_REQUEST_FAILED='UPLOAD_REQUEST_FAILED'
export const UPDATE_LOADER='UPDATE_LOADER';