export const GET_USER='GET_USER';
export const GET_USER_SUCCESS='GET_USER_SUCCESS';

export const DELETE_USER_SUCCESS='DELETE_USER_SUCCESS';
export const UPDATE_USER_SUCCESS='UPDATE_USER_SUCCESS';
export const ADD_USER_SUCCESS='ADD_USER_SUCCESS'