export const GET_USER='GET_USER';
export const GET_USER_SUCCESS='GET_USER_SUCCESS';

export const DELETE_USER='DELETE_USER';
export const DELETE_USER_SUCCESS='DELETE_USER_SUCCESS';
export const UPDATE_USER_SUCCESS='UPDATE_USER_SUCCESS';
export const UPDATE_USER='UPDATE_USER';
export const ADD_USER='ADD_USER'
export const ADD_USER_SUCCESS='ADD_USER_SUCCESS'

export const CHANGE_PASSWORD='CHANGE_PASSWORD';
export const NUEVO_MENSAJE='NUEVO_MENSAJE';
export const RESET_MENSAJE='RESET_MENSAJE'