export const LOGIN_EMAIL_REQUEST = 'LOGIN_EMAIL_REQUEST';
export const LOGIN_EMAIL_SUCCESS='LOGIN_EMAIL_SUCCESS';
export const LOGIN_EMAIL_FAILED='LOGIN_EMAIL_FAILED';
export const REGISTER_WITH_EMAIL='REGISTER_WITH_EMAIL';
export const REGISTER_WITH_EMAIL_SUCCESS='REGISTER_WITH_EMAIL_SUCCESS';
export const REGISTER_WITH_EMAIL_FAILED='REGISTER_WITH_EMAIL_FAILED';
export const LOGOUT = 'LOGOUT';
export const LOGOUT_SUCCESS='LOGOUT_SUCCESS'
 